apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: kong-gw
spec:
  selector:
    matchLabels:
      app: kong-deployment-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-deployment-pod
    spec:
      # volumes:
      #   - name: file-search-api-claim
      #     persistentVolumeClaim:
      #       claimName: file-search-api-pvc
      containers:
      - name: kong-deployment
        image: kong-gateway-kong:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
            name: http
          - containerPort: 8443
            name: https
        resources:
          limits:
            cpu: 500m
            memory: 2G
          requests:
            cpu: 100m
            memory: 512Mi
        env:
          - name: KONG_DATABASE
            value: "off"
          - name: KONG_DECLARATIVE_CONFIG
            value: /usr/local/kong/declarative/kong.yml
          - name: KONG_PLUGINS
            value: go-wait
          - name: KONG_PLUGINSERVER_NAMES
            value: go-wait
          - name: KONG_PLUGINSERVER_GO_WAIT_QUERY_CMD
            value: /usr/local/bin/go-wait -dump
          - name: KONG_LOG_LEVEL
            value: info
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
---

apiVersion: v1
kind: Service
metadata:
  name: kong-deployment-external
  namespace: kong-gw
  labels:
    name: kong-deployment
spec:
  type: NodePort
  ports:
    - name: proxy-listen
      port: 8000
      targetPort: 8000
  selector:
    name: kong-deployment
