# apiVersion: charts.helm.k8s.io/v1alpha1
# kind: Kong
# metadata:
#   name: example-kong
# spec:
#   proxy:
#     type: NodePort
#   env:
#     prefix: /kong_prefix/
#   resources:
#     limits:
#       cpu: 500m
#       memory: 2G
#     requests:
#       cpu: 100m
#       memory: 512Mi
#   ingressController:
#     enabled: true
#     ingressClass: example-ingress-class
#     installCRDs: false


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kong-deployment
#   namespace: kong-gw
#   labels:
#     name: kong-deployment
# spec:
#   minReadySeconds: 30
#   strategy:
#     type: RollingUpdate
#   replicas: 5
#   template:
#     metadata:
#       name: kong-deployment
#       labels:
#         name: kong-deployment
#     spec:
      

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: kong-gw
spec:
  selector:
    matchLabels:
      app: kong-deployment-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-deployment-pod
    spec:
      # volumes:
      #   - name: file-search-api-claim
      #     persistentVolumeClaim:
      #       claimName: file-search-api-pvc
      containers:
      - name: kong-deployment
        image: kong-demo:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
            name: http
          - containerPort: 8443
            name: https
          - containerPort: 8001
            name: admin
          - containerPort: 7946
            name: cluster
          - containerPort: 7946
            protocol: UDP
            name: cluster-udp
        resources:
          limits:
            cpu: 500m
            memory: 2G
          requests:
            cpu: 100m
            memory: 512Mi
        env:
          - name: KONG_DATABASE
            value: "off"
          - name: KONG_GO_PLUGINS_DIR
            value: /tmp/go-plugins
          - name: KONG_DECLARATIVE_CONFIG
            value: /tmp/config.yml
          - name: KONG_PLUGINS
            value: key-checker
          # - name: KONG_PROXY_LISTEN
          #   value: 0.0.0.0:8000
          # - name: kong-deployment_CLUSTER_PROFILE
          #   value: wan
          # - name: kong-deployment_DNSMASQ
          #   value: 'off'
        # envFrom:
        # - secretRef:
        #     name: dotenv
---

apiVersion: v1
kind: Service
metadata:
  name: kong-deployment-external
  namespace: kong-gw
  labels:
    name: kong-deployment
spec:
  type: NodePort
  ports:
    - name: proxy-listen
      port: 443
      targetPort: 8000
  selector:
    name: kong-deployment
